# Generated by Django 2.2.6 on 2019-10-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_raw',
            field=models.ImageField(blank=True, null=True, upload_to='article/%Y%m%d', verbose_name='图片'),
        ),
    ]
